-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 14:01:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `emp_idnum` INT NOT NULL,
  `emp_fname` VARCHAR(255) NULL,
  `emp_lname` VARCHAR(255) NULL,
  `emp_email` VARCHAR(255) NULL,
  `emp_dob` DATE NULL,
  PRIMARY KEY (`emp_idnum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `stu_id` INT NOT NULL,
  `stu_fname` VARCHAR(255) NULL,
  `stu_lname` VARCHAR(255) NULL,
  `stu_email` VARCHAR(255) NULL,
  `stu_dob` DATE NULL,
  `employee_emp_idnum` INT NOT NULL,
  PRIMARY KEY (`stu_id`, `employee_emp_idnum`),
  INDEX `fk_students_employee1_idx` (`employee_emp_idnum` ASC) VISIBLE,
  CONSTRAINT `fk_students_employee1`
    FOREIGN KEY (`employee_emp_idnum`)
    REFERENCES `mydb`.`employee` (`emp_idnum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_id` INT NOT NULL,
  `room_type` VARCHAR(255) NULL,
  `room_name` VARCHAR(255) NULL,
  `students_stu_id` INT NOT NULL,
  PRIMARY KEY (`room_id`, `students_stu_id`),
  INDEX `fk_room_students1_idx` (`students_stu_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_students1`
    FOREIGN KEY (`students_stu_id`)
    REFERENCES `mydb`.`students` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `food_id` INT NOT NULL,
  `food_nut` VARCHAR(45) NULL,
  `food_aller` VARCHAR(45) NULL,
  `food_type` VARCHAR(45) NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cafeteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cafeteria` (
  `cafeteria_id` INT NOT NULL,
  `caf_store` VARCHAR(45) NULL,
  PRIMARY KEY (`cafeteria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cafeteria_has_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cafeteria_has_food` (
  `cafeteria_cafeteria_id` INT NOT NULL,
  `food_food_id` INT NOT NULL,
  PRIMARY KEY (`cafeteria_cafeteria_id`, `food_food_id`),
  INDEX `fk_cafeteria_has_food_food1_idx` (`food_food_id` ASC) VISIBLE,
  INDEX `fk_cafeteria_has_food_cafeteria_idx` (`cafeteria_cafeteria_id` ASC) VISIBLE,
  CONSTRAINT `fk_cafeteria_has_food_cafeteria`
    FOREIGN KEY (`cafeteria_cafeteria_id`)
    REFERENCES `mydb`.`cafeteria` (`cafeteria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cafeteria_has_food_food1`
    FOREIGN KEY (`food_food_id`)
    REFERENCES `mydb`.`food` (`food_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food_has_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food_has_students` (
  `food_food_id` INT NOT NULL,
  `students_stu_id` INT NOT NULL,
  PRIMARY KEY (`food_food_id`, `students_stu_id`),
  INDEX `fk_food_has_students_students1_idx` (`students_stu_id` ASC) VISIBLE,
  INDEX `fk_food_has_students_food1_idx` (`food_food_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_has_students_food1`
    FOREIGN KEY (`food_food_id`)
    REFERENCES `mydb`.`food` (`food_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_food_has_students_students1`
    FOREIGN KEY (`students_stu_id`)
    REFERENCES `mydb`.`students` (`stu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`office` (
  `of_idnum` INT NOT NULL,
  `of_type` VARCHAR(255) NULL,
  `of_loc` VARCHAR(255) NULL,
  `of_desc` VARCHAR(255) NULL,
  `of_name` VARCHAR(255) NULL,
  PRIMARY KEY (`of_idnum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fee` (
  `fee_id` INT NOT NULL,
  `fee_refnum` VARCHAR(255) NULL,
  `fee_name` VARCHAR(255) NULL,
  `office_of_idnum` INT NOT NULL,
  PRIMARY KEY (`fee_id`, `office_of_idnum`),
  INDEX `fk_fee_office1_idx` (`office_of_idnum` ASC) VISIBLE,
  CONSTRAINT `fk_fee_office1`
    FOREIGN KEY (`office_of_idnum`)
    REFERENCES `mydb`.`office` (`of_idnum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `sal_code` INT NOT NULL,
  `sal_amount` INT NULL,
  `sal_type` VARCHAR(255) NULL,
  `office_of_idnum` INT NOT NULL,
  PRIMARY KEY (`sal_code`, `office_of_idnum`),
  INDEX `fk_salary_office1_idx` (`office_of_idnum` ASC) VISIBLE,
  CONSTRAINT `fk_salary_office1`
    FOREIGN KEY (`office_of_idnum`)
    REFERENCES `mydb`.`office` (`of_idnum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students_has_fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students_has_fee` (
  `students_stu_id` INT NOT NULL,
  `students_employee_emp_idnum` INT NOT NULL,
  `fee_fee_id` INT NOT NULL,
  PRIMARY KEY (`students_stu_id`, `students_employee_emp_idnum`, `fee_fee_id`),
  INDEX `fk_students_has_fee_fee1_idx` (`fee_fee_id` ASC) VISIBLE,
  INDEX `fk_students_has_fee_students1_idx` (`students_stu_id` ASC, `students_employee_emp_idnum` ASC) VISIBLE,
  CONSTRAINT `fk_students_has_fee_students1`
    FOREIGN KEY (`students_stu_id` , `students_employee_emp_idnum`)
    REFERENCES `mydb`.`students` (`stu_id` , `employee_emp_idnum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_has_fee_fee1`
    FOREIGN KEY (`fee_fee_id`)
    REFERENCES `mydb`.`fee` (`fee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
